import type { Metadata } from 'next';
import { Montserrat, Anton, Bonheur_Royale } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

const anton = Anton({
  variable: '--font-anton',
  weight: '400',
  style: ['normal'],
  subsets: ['latin'],
});

const bonheurRoyale = Bonheur_Royale({
  variable: '--font-bonheur-royale',
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          montserrat.variable,
          anton.variable,
          bonheurRoyale.variable,
          `antialiased`
        )}
      >
        {children}
      </body>
    </html>
  );
}
